name: Documentation Quality

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate internal Markdown links
        run: python scripts/validate_docs.py

      - name: Markdown lint
        uses: avto-dev/markdown-lint@v1
